### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by asheesh-unyscape** [opentok/screensharing-annotation-acc-pack#55]
Hi All,
I am not able to find `OneToOneCommunicator.h` file that project.  Please someone sends me the  both files `.h` and `.m`. And when I am creating new projects `OpenTok.framework` is not importing on that project.

**Comment by marinaserranomontes** [comment]
Hi, 

You can find them in the "OTAcceleratorPackUtil" Pod or in the repo: https://github.com/opentok/acc-pack-common/tree/master/ios/OTAcceleratorPackUtilProject.

**Comment by Lucashuang0802** [comment]
Hi,

The `OTScreenShareKit` depends on the `OTAcceleratorPackUtil` and `OTAnnotationKit` which will be downloaded automatically when doing `pod install`. We suggest you to specify the version number for now since we have a minor issue with the CocoaPods versioning. You should be able to fully use the library by specifying `1.0.0`.

**Comment by asheesh-unyscape** [comment]
Hi,
I am using cocoa pods 1.0.0 and i am writing the code into pod file
platform :ios, ‘9.3’
use_frameworks!
target ’OneToOneScreenShareSample’ do
pod 'OTAcceleratorPackUtil', '~> 1.0.0’
pod 'OTAnnotationKit', '~> 1.0.0’
end

but still have same error please tell me how to resolve it.

**Comment by Lucashuang0802** [comment]
I suggest you check this out: https://github.com/opentok/screensharing-annotation-acc-pack/tree/1.0.0/ios/OneToOneScreenShareSample

Obviously, we don't need `use_frameworks!` because all accelerator packs are built on top of `OpenTok` which is a static lib. Sometimes, CocoaPods might have cache problems. You can clean the cache by `pod cache clean --all`.

**Comment by asheesh-unyscape** [comment]
Hi,
I have cleaned pod cache clean command and remove use_frameworks, but it has same error and there is not coming any framework inside the project please help me

**Comment by Lucashuang0802** [comment]
I suggest you post the whole content of `Podfile` and all error messages you get from the console. That will help us and you to address the issue. 😃

**Comment by asheesh-unyscape** [comment]
This is whole content of pod file.
platform :ios, ‘9.3’
target ’OneToOneScreenShareSample’ do
pod 'OTAcceleratorPackUtil', '~> 1.0.0’
pod 'OTAnnotationKit', '~> 1.0.0’
end
and error is coming #import <OTScreenShareKit/OTScreenShareKit.h> file not found

**Comment by asheesh-unyscape** [comment]
sorry i forgot,
OTScreenShareKit/OTScreenShareKit.h

**Comment by Lucashuang0802** [comment]
First of all, I found some syntax errors from your `Podfile`. The punctuation of ` and ' are totally different to CocoaPods. And it will result in installation failure. I am wondering whether you successfully install all accelerator packs that you need. So, we would like to see error messages from what `pod install` outputted not the error messages from ***XCode***.

Again, we really suggest you to go check this out before you work on anything from your project: I suggest you check this out: https://github.com/opentok/screensharing-annotation-acc-pack/tree/1.0.0/ios/OneToOneScreenShareSample

**Comment by asheesh-unyscape** [comment]
Hi,
I have implemented opektok and SVProgressHUD framework into my projects but i am not able import OTAcceleratorPackUtil and OTAnnotationKit frameworks into my project.

**Comment by Lucashuang0802** [comment]
@asheesh-unyscape Thanks for posting your questions. However, we can't address the issue you have exactly from what you describe. We have a new template to guide you through how to create a good issue: https://github.com/opentok/screensharing-annotation-acc-pack/issues/new. Please go ahead to check it out. 😄
