### ISSUE TITLE
Tokbox ticket copy

### ISSUE THREAD

**Issue by JayTokBox** [opentok/screensharing-annotation-acc-pack#72]
Copy/Paste from Tokbox support ticket

The scenario we're interested in involves a video call between a JS webpage and an Android app, where both parties view each other’s camera and both can draw annotations directly on the camera feed. 
I saw there’s an Annotation Pack for Android (https://github.com/opentok/annotation-acc-pack/tree/master/android but there’s no sample to show its usage, and i’m having difficulties replicating the behaviour shown in the OneToOneScreenSharingSample (https://github.com/opentok/screensharing-annotation-acc-pack/tree/master/android) which is the only example app making use of annotations – but it is used in a screensharing context, not a video feed.

Do you happen to have other samples using the Annotation Pack? Is my scenario doable with the current Annotation Pack and do i have to just work with it a bit more – or is it not doable as the Pack is only for screensharing purposes?

Thank you

**Comment by Lucashuang0802** [comment]
So far, the annotation kit is not a standalone accelerator pack for Android. You can consider it as a component of the screen-share kit. We found it very interesting and useful to combine screen-share and annotation. So, we decide to provide a sample app using screen-share and annotation in general.

As for the feature you want, we have realized that it's a tour use case. We are working on it and will provide that in the future. Please let us know if you have any feedbacks or questions. 🙂
